version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.15
  build:
    commands:
      - cd /go/src/github.com/fiduciary-benchmarks/form5500/internal/utils && go build && go install
      - cd ../../
      - GOOS=linux go build -o $GOROOT/form5500
artifacts:
  files:
    - $GOROOT/form5500
