version: 0.2
phases:
  install:
    commands:
      # get and install dependencies
      - go get github.com/fiduciary-benchmarks/form5500/internal/utils && go install github.com/fiduciary-benchmarks/form5500/internal/utils
      - ls /go/src
  build:
    commands:
      - mkdir /go/src/github.com/fiduciary-benchmarks/form5500
      - cp -R . /go/src/github.com/fiduciary-benchmarks/form5500/
      - cd /go/src/github.com/fiduciary-benchmarks/form5500/internal/utils && go build && go install
      - cd ../../
      - GOOS=linux go build -o $GOROOT/form5500
artifacts:
  files:
    - $GOROOT/form5500
